-- StudyNurse v0.4.0 NON-DESTRUCTIVE UPGRADE
-- Existing study_documents data is preserved.
-- Safe to run even if v0.3.0 upgrade SQL was already executed.

create table if not exists public.study_revision_log (
  id bigint generated by default as identity primary key,
  doc_key text not null,
  payload jsonb not null,
  source_version text,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.study_revision_log enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='study_revision_log'
      and policyname='studynurse revision read'
  ) then
    create policy "studynurse revision read"
      on public.study_revision_log for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public'
      and tablename='study_revision_log'
      and policyname='studynurse revision insert'
  ) then
    create policy "studynurse revision insert"
      on public.study_revision_log for insert
      to anon, authenticated
      with check (true);
  end if;
end $$;

grant select, insert on public.study_revision_log to anon, authenticated;

-- Preserve the exact pre-v0.4.0 document once.
insert into public.study_revision_log(doc_key, payload, source_version, reason)
select d.doc_key,
       d.payload,
       coalesce(d.payload->>'version','legacy'),
       'upgrade-baseline-v0.4.0'
from public.study_documents d
where not exists (
  select 1
  from public.study_revision_log l
  where l.doc_key=d.doc_key
    and l.reason='upgrade-baseline-v0.4.0'
);

-- Ensure image bucket exists. Does not delete existing files.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'studynurse-images',
  'studynurse-images',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update
set public=excluded.public,
    file_size_limit=excluded.file_size_limit,
    allowed_mime_types=excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='studynurse image insert'
  ) then
    create policy "studynurse image insert"
      on storage.objects for insert
      to anon, authenticated
      with check (bucket_id='studynurse-images');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='studynurse image select'
  ) then
    create policy "studynurse image select"
      on storage.objects for select
      to anon, authenticated
      using (bucket_id='studynurse-images');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='storage' and tablename='objects'
      and policyname='studynurse image delete'
  ) then
    create policy "studynurse image delete"
      on storage.objects for delete
      to anon, authenticated
      using (bucket_id='studynurse-images');
  end if;
end $$;
